apiVersion: v1
kind: Service
metadata:
  name: $PROJECT_NAME
  namespace: $K8S_NAMESPACE
  labels:
    app: $PROJECT_NAME
spec:
  selector:
    app: $PROJECT_NAME
  ports:
    - protocol: TCP
      port: $K8S_SERVICE_PORT
      targetPort: $K8S_SERVICE_PORT
  type: ClusterIP
